### ISSUE TITLE
Can't boot to Big Sur or catalina 10.15.7

### ISSUE THREAD

**Issue by Thatisjigen** [bangmaple/HP-ZBook-G1-OpenCore#1]
is something in the config.plist wrong?

**Comment by bangmaple** [comment]
Hi there, thanks for creating an issue.
Please answer to me the following questions:
1. Did you manage it to boot into the OpenCore Bootloader?
2. Did you find that the kernel panic appear on your laptop when you decided to boot to the specific version of macOS.
3. If you have something like image or log attachment please show it to me.

I will be happy to resolve it for you.

Regards!

**Comment by Thatisjigen** [comment]
I have an existing HDD setup with clover and catalina 10.15.7, i managed to boot Opencore from an external usb drive(I'm using it to have my original efi untouched till i manage to boot, note: i got big sur installer in the external usb and catalina in the HDD)
I can boot only in recovery mode, here all is fine, instead when i try to boot to the existing macos installation or to the big sur installer i got the kernel panic. I'll give you an image in a few minutes, dunnow how take logs in opencore tho

Thanks for your time :)

**Comment by Thatisjigen** [comment]
![IMG_20201228_152040](https://user-images.githubusercontent.com/55486333/103220373-65c32100-4920-11eb-8eea-866b80b23ffc.jpg)

Here is what i get while booting

**Comment by bangmaple** [comment]
Hi there,

I'm also facing that issue. The booting/install process of the macOS Big Sur takes long to finish.

Please wait it for about 10-30 minutes. Whether the process is done or not, please notify me.

Regard!

**Comment by bangmaple** [comment]
Could you please also take an image of the kernel panic image. Thanks!

**Comment by bangmaple** [comment]
Please keep in mind that this is not the problem in my configuration. The macOS Big Sur itself take too long to install.

If you have any further questions, please comment.

Looking forward to hearing from you.

**Comment by bangmaple** [comment]
Currently I'm using macOS Mojave with the current configuration and I'm happy with the boot time.

I used to use macOS Catalina, macOS Big Sur but I use Mojave for my legacy applications.

Hope it be useful.

**Comment by Thatisjigen** [comment]
I don't know how it is possible but i don't think time will make it boot, as I said i got a kernel panic, it only give the same screen as in previous pic but with the apple logo in the background and all the log blurred out, so no way it may boot 

I may try the clover way (sigh) for now

You can close the issue if you want, but still the problem is there, i may send you an email if i manage to fix that👌

**Comment by bangmaple** [comment]
Hi there,

I just thought that you must clear the NVRAM memory before switching from Clover to OpenCore.

Please delete all the entries by using Hackintool app or by using the command `sudo nvram -c`

Regards.

**Comment by Thatisjigen** [comment]
Already tryed, no luck :(

**Comment by bangmaple** [comment]
Hi again,

Can you please attach your Clover configuration files in zipped file and share it to me so that I could examine yours!

Hope to hear from you soon.

**Comment by Thatisjigen** [comment]
[CLOVER.zip](https://github.com/bangmaple/HP-ZBook-G1-OpenCore/files/5748201/CLOVER.zip)

This one is the outdated one (working with latest catalina), it can't boot big sur obviously but is just smooth on catalina, boot time is 20-30 s 
If you want we can talk in any other place btw, i may sent my telegram id via mail if you want! :)

**Comment by Thatisjigen** [comment]
[efi.zip](https://github.com/bangmaple/HP-ZBook-G1-OpenCore/files/5749206/efi.zip)

After some hours i've managed to boot, some patches are missing tho, audio is dead for sure, maybe we can work together to get it smoother
![IMG_20201229_013658](https://user-images.githubusercontent.com/55486333/103250870-5ff82a80-4976-11eb-96af-3cd5e2cdc426.jpg)

**Comment by Thatisjigen** [comment]
Hi again, sorry for bothering you, I managed to boot but acpi patches seems not working(no battery stats), and HD4600 is not working properly yet


[OC.zip](https://github.com/bangmaple/HP-ZBook-G1-OpenCore/files/5750477/OC.zip)

**Comment by bangmaple** [comment]
Hi there,

Thanks for your comments.
I'm currently examining with it. I'll probably integrate with your current situation into the OC pack.

Thanks for your waiting.

Regards.

**Comment by Thatisjigen** [comment]
Updated efi uploaded btw

**Comment by bangmaple** [comment]
Hi again,

I have updated the repo resources to the latest OpenCore version and tested with macOS Big Sur Beta 11.2 Beta 2.

Regards.
